### PR TITLE
fix: fix samples and samples tests for UptimeCheck.

### LINKED ISSUE #850: com.example.monitoring.UptimeIT: test2_GetUptimeCheck failed
Note: #752 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 5df913848285ab8ccbd2e73ec13bde0d00afbbc2
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/2b98b965-7f3c-4793-8ebd-2b434c8c72f6), [Sponge](http://sponge2/2b98b965-7f3c-4793-8ebd-2b434c8c72f6)
status: failed
<details><summary>Test output</summary><br><pre>com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Unable to fetch check check-0358db in project java-docs-samples-testing
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:90)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.monitoring.v3.UptimeCheckServiceClient.getUptimeCheckConfig(UptimeCheckServiceClient.java:462)
		at com.google.cloud.monitoring.v3.UptimeCheckServiceClient.getUptimeCheckConfig(UptimeCheckServiceClient.java:436)
		at com.example.monitoring.UptimeSample.getUptimeCheckConfig(UptimeSample.java:261)
		at com.example.monitoring.UptimeSample.main(UptimeSample.java:134)
		at com.example.monitoring.UptimeIT.test2_GetUptimeCheck(UptimeIT.java:76)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
		at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
		at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
		at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
		at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Unable to fetch check check-0358db in project java-docs-samples-testing
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 17 more
</pre></details>

### LINKED ISSUE #851: com.example.monitoring.UptimeIT: test2_UpdateUptimeCheck failed
Note: #756 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 5df913848285ab8ccbd2e73ec13bde0d00afbbc2
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/2b98b965-7f3c-4793-8ebd-2b434c8c72f6), [Sponge](http://sponge2/2b98b965-7f3c-4793-8ebd-2b434c8c72f6)
status: failed
<details><summary>Test output</summary><br><pre>com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:90)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.monitoring.v3.UptimeCheckServiceClient.updateUptimeCheckConfig(UptimeCheckServiceClient.java:720)
		at com.example.monitoring.UptimeSample.updateUptimeCheck(UptimeSample.java:193)
		at com.example.monitoring.UptimeSample.main(UptimeSample.java:121)
		at com.example.monitoring.UptimeIT.test2_UpdateUptimeCheck(UptimeIT.java:70)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
		at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
		at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
		at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
		at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Requested entity was not found.
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 17 more
</pre></details>

### LINKED ISSUE #863: com.example.monitoring.UptimeIT: test2_ListUptimeChecks failed
Note: #754 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: b3154ba58c11a9fe2c9f72fd2c6602a13b518826
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/4101af1d-bbb7-4f33-b76d-eab9dc633f63), [Sponge](http://sponge2/4101af1d-bbb7-4f33-b76d-eab9dc633f63)
status: failed
<details><summary>Test output</summary><br><pre>expected to contain:
    check-a4dc68
but was:
    check-00ab2d
    check-026dfe
    check-034416
    check-0358db
    check-041658
    check-04429a
    check-084b37
    check-0981f6
    check-0c09f8
    check-0d9304
    check-0e8704
    check-0ed0b4
    check-140e03
    check-152877
    check-16c15c
    check-16ed6f
    check-1a824e
    check-1b5db4
    check-1e9419
    check-1ea1ce
    check-1f0ee0
    check-20bd69
    check-22d45b
    check-242c88
    check-3200b2
    check-3692ea
    check-3803c2
    check-3842e9
    check-390c77
    check-399a6d
    check-3d40f7
    check-3ea735
    check-421f7f
    check-430ade
    check-445900
    check-459e5f
    check-4bfe88
    check-50daad
    check-513f70
    check-546171
    check-549418
    check-5595f0
    check-568b25
    check-5755a2
    check-5898af
    check-590780
    check-59620a
    check-5bd496
    check-5eed48
    check-66eb71
    check-6a7a38
    check-7159de
    check-73c30d
    check-750b9c
    check-79b907
    check-7dc6e4
    check-83a4a9
    check-83f7da
    check-8946ad
    check-907067
    check-920886
    check-941a7a
    check-9443da
    check-9cc439
    check-9d2922
    check-9f1674
    check-a18390
    check-a6ef03
    check-ad0c2c
    check-b12bae
    check-b1b13a
    check-b2dd4e
    check-b63544
    check-b80752
    check-b85ffe
    check-b88c15
    check-bc5e71
    check-c10081
    check-c14dfd
    check-c1befa
    check-ca07b8
    check-cdee9b
    check-cec241
    check-cee715
    check-cf38de
    check-d0699b
    check-d08df2
    check-d151ae
    check-d1a6dc
    check-d2ff5e
    check-d40a0a
    check-db38b4
    check-dbf105
    check-dbf301
    check-df9b8b
    check-ec1a08
    check-ee977a
    check-eecbed
    check-efe630
    check-f3b81e
    check-f8a853
    check-fa55fb
    check-fa9d9b
    check-ffaf13
    
	at com.example.monitoring.UptimeIT.test2_ListUptimeChecks(UptimeIT.java:83)
</pre></details>

### LINKED ISSUE #871: com.example.monitoring.UptimeIT: test1_CreateUptimeCheck failed
Note: #862 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 7d3c78c56bc46ba502c30b12341fcb4cdc7503ad
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/41ee0ece-7067-4b82-8c98-4e74953e7e80), [Sponge](http://sponge2/41ee0ece-7067-4b82-8c98-4e74953e7e80)
status: failed
<details><summary>Test output</summary><br><pre>com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Error creating uptime check config: too many configs in project
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:100)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:572)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:468)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:432)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:465)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.monitoring.v3.UptimeCheckServiceClient.createUptimeCheckConfig(UptimeCheckServiceClient.java:671)
		at com.example.monitoring.UptimeSample.createUptimeCheck(UptimeSample.java:164)
		at com.example.monitoring.UptimeSample.main(UptimeSample.java:114)
		at com.example.monitoring.UptimeIT.test1_CreateUptimeCheck(UptimeIT.java:64)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
		at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
		at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
		at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
		at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Error creating uptime check config: too many configs in project
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 17 more
</pre></details>

### PR DESCRIPTION
**Pull request by blakeli0**
UpdateUptimeCheck, GetUptimeCheck and DeleteUptimeCheck have been failing because they are not taking the correct argument, instead of passing in display name, we should pass in the full check name. Hence every time the test was triggered, a new uptime check was created but was not cleaned up correctly, eventually we reached the limit of uptime check in the testing project and CreateUptimeCheck started failing too.
fixes #850 
fixes #851 
fixes #863 
fixes #871

### CODE REVIEW

File: samples/snippets/src/main/java/com/example/monitoring/UptimeSample.java [hunk 1]
```diff
@@ -273,10 +268,9 @@ private static void getUptimeCheckConfig(String projectId, String checkName) thr
   // [END monitoring_uptime_check_get]]
 
   // [START monitoring_uptime_check_delete]]
-  private static void deleteUptimeCheckConfig(String projectId, String checkName)
-      throws IOException {
+  private static void deleteUptimeCheckConfig(String checkName) throws IOException {
     try (UptimeCheckServiceClient client = UptimeCheckServiceClient.create()) {
-      client.deleteUptimeCheckConfig(UptimeCheckConfigName.format(projectId, checkName));
+      client.deleteUptimeCheckConfig(checkName);
```
Comment (averikitsch) [inline samples/snippets/src/main/java/com/example/monitoring/UptimeSample.java:273]: When I tried this sample, there was a difference in using the full resource name or ID vs the display name. Can we make it more clear how to get the id vs display name and when they need to be used?

Comment (blakeli0) [reply samples/snippets/src/main/java/com/example/monitoring/UptimeSample.java:273]: I don't see a way to do it using display name anymore. The full check name is in the format of `projects/[PROJECT_ID_OR_NUMBER]/uptimeCheckConfigs/[UPTIME_CHECK_ID]`, where I guess `UPTIME_CHECK_ID` used to be display name, hence the tests were written this way. Now the `UPTIME_CHECK_ID` is display name plus a random string(probably generated in the backend), e.g. `check-cf3bd1` vs `check-cf3bd1-Pn123Zpa-k4`, so all the tests started failing because unable to find the uptime check. The `UPTIME_CHECK_ID` can be retrieved simply by `UptimeCheckConfig#getName()`, I can provide some comments if you think it's necessary.

**Review by averikitsch — APPROVED** [review]
